# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 309efea04f13d38c3c251448c3c7509b4cab9baef8fcb951fd037e1e331846238e9d5d488b99a36b24e61213010b648b4ff911ec753982e6eace854c75f79211

test:
  secret_key_base: 036056909d364b99e3f5cabc574a239f4eb147eb205c9a29717506b93d3ce8273805b5cce1de2fa0fc770b5a4687ecfd3ceb43009eb9a81dcba65009b6c9fc80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
